"""add admin fields

Revision ID: 17329443f196
Revises: a12ff327873a
Create Date: 2025-08-04 21:07:35.385221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17329443f196'
down_revision: Union[str, Sequence[str], None] = 'a12ff327873a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('forms_addiction_type_key'), 'forms', type_='unique')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.create_unique_constraint(op.f('forms_addiction_type_key'), 'forms', ['addiction_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('forms', 'is_active')
    # ### end Alembic commands ###
