"""usuniecie testowej kolumny

Revision ID: 47451191daa0
Revises: a236c187347e
Create Date: 2025-07-27 18:55:02.135629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47451191daa0'
down_revision: Union[str, Sequence[str], None] = 'a236c187347e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_columns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_columns', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
