"""user login verification columns2

Revision ID: 67a7bef3f42f
Revises: a1d8b0b1cd81
Create Date: 2025-07-27 20:12:29.029446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a7bef3f42f'
down_revision: Union[str, Sequence[str], None] = 'a1d8b0b1cd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
