"""new answers model

Revision ID: 968179cab9bd
Revises: 17329443f196
Create Date: 2025-08-06 20:38:06.785835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '968179cab9bd'
down_revision: Union[str, Sequence[str], None] = '17329443f196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_submissions')
    op.add_column('answers', sa.Column('question_id', sa.UUID(), nullable=False))
    op.add_column('answers', sa.Column('value', sa.JSON(), nullable=False))
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.drop_column('answers', 'answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'created_at')
    op.drop_column('answers', 'value')
    op.drop_column('answers', 'question_id')
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('form_submissions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('form_submissions_pkey'))
    )
    # ### end Alembic commands ###
