"""user login verification columns

Revision ID: a1d8b0b1cd81
Revises: 47451191daa0
Create Date: 2025-07-27 20:00:02.896583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d8b0b1cd81'
down_revision: Union[str, Sequence[str], None] = '47451191daa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE users SET failed_attempts = 0 WHERE failed_attempts IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('blocked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_until')
    op.drop_column('users', 'failed_attempts')
    # ### end Alembic commands ###
