"""Dodanie testowej kolumny

Revision ID: a236c187347e
Revises: 1340c02eebb3
Create Date: 2025-07-27 18:47:00.700924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a236c187347e'
down_revision: Union[str, Sequence[str], None] = '1340c02eebb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_columns', sa.String(), nullable=True))
    op.alter_column('users', 'addiction_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'addiction_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'test_columns')
    # ### end Alembic commands ###
