"""user profile table

Revision ID: d76f72c20486
Revises: 968179cab9bd
Create Date: 2025-08-08 20:56:44.169482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd76f72c20486'
down_revision: Union[str, Sequence[str], None] = '968179cab9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('tried_quitting', sa.Boolean(), nullable=False),
    sa.Column('quitting_reason', sa.String(), nullable=False),
    sa.Column('quitting_strategy', sa.Enum('IMMEDIATELY', 'GRADUAL_REDUCTION', 'MEDICATION', 'BEHAVIORAL_THERAPY', 'COMBINATION', 'UNDECIDED', name='quitstage'), nullable=False),
    sa.Column('determination_scale', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('determination_scale >= 1 AND determination_scale <= 10', name='determination_scale_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
